# Generated by Django 4.0.6 on 2022-10-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assignteach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.TextField(max_length=10)),
                ('section', models.TextField(max_length=10)),
                ('subjectname', models.TextField(max_length=50)),
                ('teacher', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'assignteach',
            },
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regnum', models.TextField(max_length=50)),
                ('semester', models.TextField(max_length=10)),
                ('section', models.TextField(max_length=10)),
                ('subjectname', models.TextField(max_length=50)),
                ('teacher', models.TextField(max_length=50)),
                ('rating', models.TextField(max_length=10)),
                ('suggestion', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='ourteachers',
            fields=[
                ('tid', models.TextField(primary_key=True, serialize=False)),
                ('tname', models.TextField(max_length=50)),
                ('tmail', models.EmailField(max_length=50)),
            ],
            options={
                'db_table': 'ourteachers',
            },
        ),
        migrations.CreateModel(
            name='registeredstudent',
            fields=[
                ('studentid', models.TextField(primary_key=True, serialize=False)),
                ('studentmail', models.EmailField(max_length=50)),
                ('studentname', models.TextField(max_length=100)),
                ('studentsem', models.TextField(max_length=100)),
                ('studentsec', models.TextField(max_length=100)),
                ('studentpass', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'registeredstudent',
            },
        ),
        migrations.CreateModel(
            name='registeredteacher',
            fields=[
                ('tid', models.TextField(primary_key=True, serialize=False)),
                ('tmail', models.EmailField(max_length=50)),
                ('tname', models.TextField(max_length=100)),
                ('qualification', models.TextField(max_length=100)),
                ('mobile', models.TextField(max_length=100)),
                ('password', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'registeredteacher',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('studentid', models.TextField(primary_key=True, serialize=False)),
                ('studentname', models.TextField(max_length=50)),
                ('studentmail', models.EmailField(max_length=50)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('subject', models.TextField(primary_key=True, serialize=False)),
                ('sem', models.IntegerField()),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
    ]
